chain_width = 80
comment_width = 120
fn_call_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "Horizontal"
match_block_trailing_comma = true
max_width = 120
reorder_imports = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
