[package]
name = "slang"
version = "0.1.0"
edition = "2021"

[dependencies]
stackz = { path = "../stackz" }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
derive_more = { version = "1", default-features = false, features = ["deref", "deref_mut", "display"] }
